version: '3.8'
services:
  maven:
    build: mavenbuild
    volumes:
      - DCPBL:/Docker-C/maven
  prod:
    image: tomcat:alpine
    volumes:
      - DCPBL:/Docker-C/tomcat
    ports:
      - "8080:80"
volumes:
  DCPBL:

