version: '3.8'
services:
  maven:
    build: mavenbuild
    ports: 
      - "8080:80"
    volumes:
      - ./tomcat:/var/lib/tomcat
  ##prod:
    ##image: tomcat:alpine
    ##volumes_from:
     ## - maven
  ##  ports:
    ##  - "8080:80"

