FROM ubuntu:18.04
RUN apt update
RUN apt-get install maven -y
RUN apt-get install git -y
WORKDIR /tmp/
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR /tmp/boxfuse-sample-java-war-hello
RUN mvn package