##FROM maven:3.8-openjdk-11
##RUN apt-get update
##RUN apt-get install maven -y
##RUN apt-get install git -y
##WORKDIR /tmp/
##RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
##WORKDIR /tmp/boxfuse-sample-java-war-hello
##RUN mvn package
##WORKDIR /tpm/boxfuse-sample-java-war-hello/target
FROM tomcat:9.0
RUN apt update
RUN apt install maven -y
RUN apt install git -y
WORKDIR /tmp/
RUN git clone https://github.com/boxfuse/boxfuse-sample-java-war-hello.git
WORKDIR /tmp/boxfuse-sample-java-war-hello/
RUN mvn package
WORKDIR /tmp/boxfuse-sample-java-war-hello/target/
RUN cp hello-1.0.war /usr/local/tomcat/webapps